# Generated by Django 3.2.20 on 2023-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_auto_20230825_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=10, null=True),
        ),
    ]
