# Generated by Django 3.2.20 on 2023-08-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_auto_20230825_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='manufacturer',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='pack',
            new_name='packing',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other Product'), ('POWDER', 'Powder'), ('SERVICE', 'Service'), ('SYRUP', 'Syrup / Suspensions'), ('TABLET', 'Tablet')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='conversion_case',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='conversion_strip',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='salt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.salt'),
        ),
    ]
